# Generated by Django 2.2.19 on 2021-06-21 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtask',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedtask',
            name='repeatability',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
