# Generated by Django 2.2.19 on 2021-06-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0002_auto_20210621_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
