# Generated by Django 2.2.19 on 2021-06-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0004_plannedtask_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedtask',
            old_name='start_time',
            new_name='next_start_time',
        ),
    ]
