# Generated by Django 2.2.19 on 2021-06-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0005_auto_20210629_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtask',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
