# Generated by Django 2.2.19 on 2021-08-23 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0006_auto_20210630_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=40)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='plannedtask',
            name='custom_weekdays',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='plannedtask',
            name='name',
            field=models.CharField(default=datetime.datetime(2021, 8, 23, 12, 33, 50, 648425), max_length=2000),
            preserve_default=False,
        ),
    ]
