# Generated by Django 2.2.19 on 2021-08-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0007_auto_20210823_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtask',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
