# Generated by Django 2.2.19 on 2021-08-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0008_auto_20210823_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDate',
        ),
    ]
