# Generated by Django 2.2.19 on 2021-08-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0009_delete_customdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtask',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_task', to='job.Job'),
        ),
    ]
