# Generated by Django 2.2.19 on 2021-09-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0010_auto_20210825_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtask',
            name='repeatability',
            field=models.CharField(blank=True, choices=[('run_once', 'RUN_ONCE'), ('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('monthly_date', 'MONTHLY_DATE'), ('monthly_week_day', 'MONTHLY_WEEK_DAY'), ('monthly_last_week_day', 'MONTHLY_LAST_WEEK_DAY'), ('on_week_days', 'ON_WEEK_DAYS')], max_length=40),
        ),
    ]
