version: '3.8'

services:
  vault:
    image: vault:1.7.2
    command: vault server -dev -dev-listen-address="0.0.0.0:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"

  rabbitmq:
    build:
      context: ./CI
      dockerfile: rabbitmq.Dockerfile

  xorg:
    build:
      context: ./CI
      dockerfile: xorg.Dockerfile

  nginx:
    build:
      context: ./CI
      dockerfile: nginx.Dockerfile

  db:
    ports:
      - '5432:5432'

  server:
    build:
      context: .
      dockerfile: CI/app.Dockerfile
    volumes:
      - .:/app

  worker_longlived:
    build:
        context: .
        dockerfile: CI/app.Dockerfile
    volumes:
      - .:/app
    environment:
      - THREAD_COUNT=1

  worker_shortlived:
    build:
        context: .
        dockerfile: CI/app.Dockerfile
    volumes:
      - .:/app

  worker_rabbitmq_receiver:
    build:
      context: .
      dockerfile: CI/app.Dockerfile
    volumes:
      - .:/app

  worker_shortlived_realtime:
    build:
      context: .
      dockerfile: CI/app.Dockerfile
    volumes:
      - .:/app

  worker_celery_beat:
    build:
      context: .
      dockerfile: CI/app.Dockerfile
    volumes:
      - .:/app

  cache:
    build:
      context: ./CI
      dockerfile: cache.Dockerfile

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
#          ip_range: 172.28.5.0/24
#          gateway: 172.28.5.254
#          aux_addresses:
#            host1: 172.28.1.5
#            host2: 172.28.1.6
#            host3: 172.28.1.7