# Generated by Django 2.2.5 on 2020-11-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('framework_data', '0001_initial'),
        ('job', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_task_id', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('page_after_login', models.BooleanField(default=False)),
                ('options', models.CharField(default='', max_length=4000)),
                ('commands', models.CharField(default='', max_length=4000)),
            ],
            options={
                'db_table': 'activity_task',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now=True)),
                ('celery_task_id', models.CharField(max_length=100, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('progress', models.CharField(max_length=2000, null=True)),
                ('result', models.TextField(null=True)),
                ('last_reported', models.DateTimeField(null=True)),
                ('log', models.TextField(null=True)),
                ('target_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('test_results', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='framework_data.TestResults')),
            ],
            options={
                'db_table': 'task',
                'get_latest_by': 'date_started',
            },
        ),
        migrations.CreateModel(
            name='WorkerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
            options={
                'db_table': 'worker_key',
            },
        ),
        migrations.CreateModel(
            name='SitemapTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'db_table': 'sitemap_task',
            },
        ),
    ]
