# Generated by Django 2.2.5 on 2020-12-15 15:43

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Lower, Upper


def forwards_make_tasks_statuses_lowercase(apps, schema_editor):
    Task = apps.get_model('task', 'Task')
    db_alias = schema_editor.connection.alias
    Task.objects.using(db_alias).update(status=Lower(F('status')))


def reverse_make_tasks_statuses_lowercase(apps, schema_editor):
    Task = apps.get_model('task', 'Task')
    db_alias = schema_editor.connection.alias
    Task.objects.using(db_alias).update(status=Upper(F('status')))


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_make_tasks_statuses_lowercase, reverse_make_tasks_statuses_lowercase),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('running', 'RUNNING'), ('aborted', 'ABORTED'), ('crashed', 'CRASHED'), ('success', 'SUCCESS'), ('queued', 'QUEUED')], max_length=16),
        ),
    ]
