# Generated by Django 2.2.5 on 2020-12-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201215_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_started',
            field=models.DateTimeField(null=True),
        ),
    ]
