# Generated by Django 2.2.19 on 2021-09-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20201220_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaptask',
            name='message',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitemaptask',
            name='status',
            field=models.CharField(choices=[('running', 'RUNNING'), ('failed', 'FAILED'), ('finished', 'FINISHED'), ('finished_with_problems', 'FINISHED_WITH_PROBLEMS')], default='finished', max_length=32),
            preserve_default=False,
        ),
    ]
