# Generated by Django 2.2.19 on 2021-09-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210901_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='generated_report',
            field=models.FileField(null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('running', 'RUNNING'), ('aborted', 'ABORTED'), ('crashed', 'CRASHED'), ('success', 'SUCCESS'), ('queued', 'QUEUED'), ('report_generating', 'REPORT_GENERATING')], max_length=16),
        ),
    ]
