# Generated by Django 2.2.19 on 2021-09-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20210916_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('running', 'RUNNING'), ('aborted', 'ABORTED'), ('crashed', 'CRASHED'), ('success', 'SUCCESS'), ('queued', 'QUEUED'), ('report_generating', 'REPORT_GENERATING')], max_length=20),
        ),
    ]
