# Generated by Django 2.2.19 on 2021-09-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20210916_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
