# Generated by Django 2.2.19 on 2021-09-22 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20210916_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='generated_report',
        ),
        # migrations.AlterField(
        #     model_name='task',
        #     name='message',
        #     field=models.CharField(blank=True, max_length=255),
        # ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('running', 'RUNNING'), ('aborted', 'ABORTED'), ('crashed', 'CRASHED'), ('success', 'SUCCESS'), ('queued', 'QUEUED')], max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'SUCCESS'), ('queued', 'QUEUED'), ('generating', 'GENERATING')], max_length=20)),
                ('generated_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('delta_starting_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_starting_from', to='task.Task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='task.Task')),
            ],
        ),
    ]
