# Generated by Django 2.2.19 on 2021-09-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20210929_0918'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='task',
        #     name='generated_report',
        #     field=models.FileField(blank=True, null=True, upload_to='reports/'),
        # ),
    ]
