# Generated by Django 2.2.19 on 2021-09-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20210929_1048'),
        ('task', '0008_auto_20210929_0939'),
    ]

    operations = [
    ]
