# Generated by Django 2.2.19 on 2021-11-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_merge_20210929_1912'),
        ('task', '0007_auto_20210922_0919'),
    ]

    operations = [
    ]
