# Generated by Django 2.2.19 on 2021-12-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_merge_20211109_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_testing_time',
            field=models.IntegerField(null=True),
        ),
    ]
