# Generated by Django 2.2.19 on 2022-01-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0011_task_estimated_testing_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="estimated_testing_time",
        ),
    ]
