# Generated by Django 2.2.5 on 2020-12-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_parent_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_size_data',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
