# Generated by Django 2.2.5 on 2021-02-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_page_page_size_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_after_login',
        ),
    ]
