# Generated by Django 2.2.19 on 2021-08-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0007_auto_20210806_0945'),
        ('issue', '0005_auto_20210504_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIntegrationParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=512)),
                ('jira_project_key', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'db_table': 'jira_integration',
            },
        ),
        migrations.CreateModel(
            name='JiraTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(max_length=64)),
                ('jira_task_key', models.CharField(max_length=128)),
                ('added_examples', models.ManyToManyField(to='issue.Example')),
                ('jira_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.JiraIntegrationParams')),
            ],
            options={
                'db_table': 'jira_task',
            },
        ),
    ]
