# Generated by Django 2.2.19 on 2021-09-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_merge_20210929_1912'),
        ('jira', '0002_auto_20210929_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraWorkerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'RUNNING'), ('failed', 'FAILED'), ('success', 'SUCCESS'), ('queued', 'QUEUED')], default='queued', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('total_examples', models.IntegerField(default=0)),
                ('processed_examples', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
        ),
    ]
