# Generated by Django 2.2.19 on 2021-10-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_jiraworkertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraintegrationparams',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_integration_params', to='project.Project'),
        ),
    ]
