# Generated by Django 2.2.19 on 2021-10-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0006_auto_20211001_1225'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jiraworkertask',
            table=None,
        ),
    ]
