# Generated by Django 2.2.19 on 2021-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0007_auto_20211004_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraworkertask',
            name='total_issues',
            field=models.IntegerField(default=0),
        ),
    ]
