# Generated by Django 2.2.19 on 2021-10-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0008_jiraworkertask_total_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraworkertask',
            name='issues_reopened',
            field=models.IntegerField(default=0),
        ),
    ]
