# Generated by Django 2.2.19 on 2021-10-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0010_auto_20211013_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jiraworkertask',
            old_name='duplicate_issues',
            new_name='duplicated_issues',
        ),
    ]
