# Generated by Django 2.2.5 on 2020-12-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletest',
            name='time_data',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
