# Generated by Django 2.2.5 on 2021-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework_data', '0003_testtiming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('NOTRUN', 'NOTRUN'), ('WARN', 'WARN'), ('NOELEMENTS', 'NOELEMENTS'), ('ERROR', 'ERROR'), ('FAIL', 'FAIL'), ('READY', 'READY'), ('PASS', 'PASS')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='testtiming',
            table='test_timing',
        ),
    ]
