# Generated by Django 2.2.19 on 2021-04-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework_data', '0004_auto_20210201_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'available_test_group',
            },
        ),
        migrations.AddField(
            model_name='availabletest',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='available_tests', to='framework_data.AvailableTestGroup'),
        ),
    ]
