# Generated by Django 2.2.19 on 2022-01-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework_data", "0005_available_test_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="estimated_testing_time",
            field=models.IntegerField(null=True),
        ),
    ]
