# Generated by Django 2.2.19 on 2022-03-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework_data', '0007_test_estimated_screenshooting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtiming',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testtiming',
            name='page_size_data',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
