# Generated by Django 2.2.19 on 2021-03-01 10:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoPermissions',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demo_permissions', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('projects_quota', models.PositiveIntegerField(default=1)),
                ('pages_quota', models.PositiveIntegerField(default=3)),
                ('jobs_quota', models.PositiveIntegerField(default=2)),
                ('available_tests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('available_reports', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('updated_stamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'demo_permissions',
            },
        ),
    ]
