# Generated by Django 2.2.19 on 2021-03-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_demopermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='demopermissions',
            name='is_reports_readonly',
            field=models.BooleanField(default=True),
        ),
    ]
