# Generated by Django 2.2.19 on 2021-03-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_demopermissions_is_reports_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='demopermissions',
            name='running_jobs_quota',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='demopermissions',
            name='jobs_quota',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
