# Generated by Django 2.2.5 on 2020-11-30 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test Job', max_length=1000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('test_list', models.CharField(default='', max_length=4000)),
                ('audit_report', models.CharField(default='', max_length=4000)),
                ('vpat_report', models.CharField(default='', max_length=4000)),
                ('last_test', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pages', models.ManyToManyField(to='page.Page')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='project.Project')),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
