# Generated by Django 2.2.5 on 2020-12-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='estimated_testing_time',
            field=models.FloatField(null=True),
        ),
    ]
