# Generated by Django 2.2.5 on 2021-01-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_estimated_testing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='audit_report',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vpat_report',
        ),
    ]
