# Generated by Django 2.2.19 on 2022-01-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210118_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resolutions',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
