# Generated by Django 2.2.19 on 2022-01-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_resolutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='resolutions',
        ),
    ]
