# Generated by Django 2.2.19 on 2022-01-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_job_resolutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resolutions',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
