# Generated by Django 2.2.19 on 2022-01-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_resolutions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='resolutions',
            new_name='page_resolution',
        ),
    ]
