# Generated by Django 2.2.19 on 2022-01-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20220124_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='page_resolution',
            new_name='resolutions',
        ),
    ]
