# Generated by Django 2.2.19 on 2022-01-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20220124_0951'),
        ('job', '0004_auto_20211226_1557'),
    ]

    operations = [
    ]
