# Generated by Django 2.2.5 on 2020-11-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('click_sequence', models.CharField(max_length=2000, null=True)),
                ('side_file', models.FileField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
