# Generated by Django 2.2.19 on 2021-06-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='original_filename',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
