# Generated by Django 2.2.19 on 2021-06-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_original_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='original_filename',
            new_name='filename',
        ),
    ]
