# Generated by Django 2.2.19 on 2022-02-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20210603_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='page_resolution',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
