# Generated by Django 2.2.19 on 2022-02-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_activity_page_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='page_resolution',
        ),
    ]
