# Generated by Django 2.2.19 on 2022-02-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_remove_activity_page_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='page_resolution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
