# Generated by Django 2.2.5 on 2020-11-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
        ('framework_data', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err_id', models.CharField(max_length=50)),
                ('problematic_element_selector', models.CharField(max_length=500)),
                ('code_snippet', models.TextField()),
                ('severity', models.CharField(default='FAIL', max_length=20)),
                ('steps', models.TextField(null=True)),
                ('actual_result', models.CharField(max_length=10000, null=True)),
                ('note', models.CharField(max_length=10000, null=True)),
                ('expected_result', models.CharField(max_length=10000, null=True)),
                ('number_in_task', models.IntegerField(null=True)),
                ('force_best_practice', models.BooleanField(default=False)),
                ('order_in_issuegroup', models.IntegerField(default=1)),
                ('recommendations', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('issue_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='report.IssueGroup')),
                ('pages', models.ManyToManyField(to='page.Page')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='framework_data.Test')),
                ('test_results', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='framework_data.TestResults')),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='PageScreenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Page')),
                ('test_results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework_data.TestResults')),
            ],
            options={
                'db_table': 'page_screenshot',
            },
        ),
        migrations.CreateModel(
            name='IssueScreenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(null=True, upload_to='images/reports/')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.Issue')),
            ],
            options={
                'db_table': 'issue_screenshot',
            },
        ),
    ]
