# Generated by Django 2.2.5 on 2021-02-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework_data', '0004_auto_20210201_1500'),
        ('report', '0004_rename_field_issue_group_to_issue_groups'),
        ('page', '0003_page_page_size_data'),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue',
            new_name='Example',
        ),
        migrations.RenameModel(
            old_name='IssueScreenshot',
            new_name='ExampleScreenshot',
        ),
    ]
