# Generated by Django 2.2.5 on 2021-02-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20210211_1239'),
        ('issue', '0002_auto_20210211_1239'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='example',
            table='example',
        ),
        migrations.AlterModelTable(
            name='examplescreenshot',
            table='example_screenshot',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='issue_group',
            new_name='issue',
        ),
        migrations.AlterField(
            model_name='example',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examples',
                                    to='report.Issue'),
        ),
    ]
