# Generated by Django 2.2.19 on 2021-03-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20210216_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplescreenshot',
            old_name='issue',
            new_name='example',
        ),
    ]
