# Generated by Django 2.2.19 on 2022-01-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_example_problematic_element_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplescreenshot',
            name='resolutions',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
