# Generated by Django 2.2.19 on 2022-01-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_example_problematic_element_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='important_example',
            field=models.BooleanField(default=True),
        ),
    ]
