# Generated by Django 2.2.19 on 2022-01-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_auto_20220119_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplescreenshot',
            name='resolution',
        ),
    ]
