# Generated by Django 2.2.19 on 2022-01-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0010_examplescreenshot_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplescreenshot',
            name='resolution',
        ),
        migrations.AddField(
            model_name='example',
            name='resolution',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
