# Generated by Django 2.2.19 on 2022-01-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_auto_20220119_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplescreenshot',
            name='resolution',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
