# Generated by Django 2.2.19 on 2022-01-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0013_auto_20220122_0348'),
        ('issue', '0007_example_important_example'),
    ]

    operations = [
    ]
