# Generated by Django 2.2.5 on 2021-01-13 12:23
# fixed by Makarova on 2021-01-13 - add update_field

from django.apps import apps
from django.db import migrations, models
import django.db.models.deletion


def update_field(apps, schema_editor):
    Conformancelevel = apps.get_model('report', 'Conformancelevel')
    levels = Conformancelevel.objects.all()
    for level in levels:
        if level.report_params:
            level.test_results = level.report_params.test_results
            level.save()


class Migration(migrations.Migration):

    dependencies = [
        ('framework_data', '0003_testtiming'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformancelevel',
            name='test_results',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='framework_data.TestResults'),
        ),
        migrations.AlterField(
            model_name='conformancelevel',
            name='report_params',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.AuditReportParams'),
        ),
        migrations.RunPython(update_field)
    ]
