# Generated by Django 2.2.19 on 2021-03-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework_data', '0004_auto_20210201_1500'),
        ('report', '0006_auto_20210217_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('test_results', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='framework_data.TestResults')),
            ],
            options={
                'db_table': 'issue_label',
                'unique_together': {('test_results', 'name')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='issues', to='report.IssueLabel'),
        ),
    ]
