# Generated by Django 2.2.19 on 2021-03-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20210310_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='test_results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='framework_data.TestResults'),
        ),
    ]
