# Generated by Django 2.2.19 on 2021-04-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20210329_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuelabel',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='issuelabel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='issuelabel',
            constraint=models.UniqueConstraint(condition=models.Q(('test_results__isnull', False), ('read_only', False)), fields=('name', 'read_only', 'test_results'), name='unique_test_results_labels'),
        ),
        migrations.AddConstraint(
            model_name='issuelabel',
            constraint=models.UniqueConstraint(condition=models.Q(('test_results__isnull', True), ('read_only', True)), fields=('name', 'read_only'), name='unique_read_only_labels'),
        ),
    ]
