# Generated by Django 2.2.19 on 2021-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_issue_label_read_only_field_and_constraints_with_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpatreportparams',
            name='product_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
