# Generated by Django 2.2.5 on 2020-11-30 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('options', models.CharField(default='', max_length=4000)),
                ('version', models.CharField(default='', max_length=255)),
                ('contact', models.CharField(default='', max_length=255)),
                ('company', models.CharField(default='', max_length=255)),
                ('testers', models.CharField(default='', max_length=255)),
                ('visual_impairments', models.BooleanField(default=False)),
                ('url', models.CharField(default='', max_length=255)),
                ('audit_report', models.CharField(default='', max_length=4000)),
                ('vpat_report', models.CharField(default='', max_length=4000)),
                ('test_list', models.CharField(default='', max_length=4000)),
                ('last_test', models.DateTimeField(blank=True, null=True)),
                ('request_interval', models.IntegerField(default=0)),
                ('enable_content_blocking', models.BooleanField(default=True)),
                ('enable_popup_detection', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_permission',
                'unique_together': {('project', 'user', 'role')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(through='project.ProjectPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
