# Generated by Django 2.2.5 on 2021-02-01 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_role_field_to_fk_model(apps, schema_editor):
    ProjectRole = apps.get_model('project', 'ProjectRole')
    ProjectPermission = apps.get_model('project', 'ProjectPermission')
    db_alias = schema_editor.connection.alias
    project_role, _ = ProjectRole.objects.using(db_alias).get_or_create(name='Admin')
    for project_permission in ProjectPermission.objects.using(db_alias).all():
        project_permission.role = project_role
        project_permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'project_role',
            },
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permissions', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectpermission',
            unique_together={('project', 'user')},
        ),
        migrations.RemoveField(
            model_name='projectpermission',
            name='role',
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='project_permissions', to='project.ProjectRole'),
        ),
        migrations.RunPython(migrate_role_field_to_fk_model),
        migrations.AlterField(
            model_name='projectpermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_permissions',
                                    to='project.ProjectRole'),
        ),
        migrations.AlterUniqueTogether(
            name='projectpermission',
            unique_together={('project', 'user', 'role')},
        ),
    ]
