# Generated by Django 2.2.5 on 2021-02-01 15:01

from django.db import migrations, models
import django.utils.timezone
from django.db.models import F


def fill_created_stamp_field_from_updated_stamp_field(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    db_alias = schema_editor.connection.alias
    Project.objects.using(db_alias).all().update(
        created_stamp=F('updated_stamp')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_refactored_project_role_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disclaimer',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.RenameField(
            model_name='project',
            old_name='date_created',
            new_name='updated_stamp',
        ),
        migrations.AddField(
            model_name='project',
            name='created_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(fill_created_stamp_field_from_updated_stamp_field)
    ]
