# Generated by Django 2.2.5 on 2021-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_disclaimer_and_time_stamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='page_after_login',
            field=models.BooleanField(default=False),
        ),
    ]
