# Generated by Django 2.2.19 on 2021-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_page_after_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disable_parallel_testing',
            field=models.BooleanField(default=False),
        ),
    ]
