# Generated by Django 2.2.19 on 2021-06-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_disable_parallel_testing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='options',
            new_name='_options',
        ),
    ]
