# Generated by Django 2.2.19 on 2021-06-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210611_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='_options',
            field=models.CharField(default='{"auth_required": false, "auth_setting": "{}"}', max_length=4000),
        ),
    ]
