# Generated by Django 2.2.19 on 2021-09-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210630_2106'),
        ('project', '0007_auto_20210806_0945'),
    ]

    operations = [
    ]
